config/routes.rb
LearnItTest1::Application.routes.draw do
  get 'learn-ios-games' => 'learn#iphone_game', :as => :learn_ios
  get 'learn-java' => 'learn#java', :as => :learn_java
  get 'backetball' => "learn#backetball", :as => :learn_basketball
  root :to => 'learn#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/learn_controller.rb
class LearnController < ApplicationController

  def iphone_game
  end

  def index
  end

  def backetball
  end

  def java
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learn_helper.rb
module LearnHelper
  def duplicate_link_to url, action
    link_to url,url, :onclick => "recordOutboundLink(this, 'Outbound Links', '#{action}');return false;"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>學習影片整理</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33141342-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  function recordOutboundLink(link, category, action) {
    _gat._getTrackerByName()._trackEvent(category, action);
    setTimeout('document.location = "' + link.href + '"', 100);
  }

</script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/learn/backetball.html.haml
.container
  /
    Masthead
    \==================================================
  %header#overview.jumbotron.subhead
    %h1 
    %p.lead 整理籃球教學影片
    .subnav.subnav-fixed
      %ul.nav.nav-pills
        %li
          %a{:href => "#global"} 跳躍力訓練
        %li
          %a{:href => "#gridSystem"} 喬丹籃球教學
        %li
          %a{:href => "#gridSystem2"} Nike Signature Moves

  %section#global
    .page-header
      %h1
        跳躍力訓練
        %small 很知名的跳躍力訓練方式
      %object{:style => "height: 390px; width: 640px"}
        %param{:name => "movie", :value => "http://www.youtube.com/v/5cHYSJUOPn0?version=3&feature=player_detailpage"}
          %param{:name => "allowFullScreen", :value => "true"}
            %param{:name => "allowScriptAccess", :value => "always"}
              %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/5cHYSJUOPn0?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
  %section#gridSystem
    .page-header
      %h1
        喬丹籃球教學
        %small 籃球大帝教你打籃球！！
    第一部：進攻 (三威脅姿勢 , 過人)
    %br
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/t-nW3ViPnYc?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/t-nW3ViPnYc?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
    %br
    第二部：罰球
    %br
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/OuadhQZPsvo?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/OuadhQZPsvo?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
    %br
    第三部：後仰跳投
    %br  
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/X3dKEzkPBJQ?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/X3dKEzkPBJQ?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
    %br
    第四部：防守
    %br
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/DQ7F4_MiHm0?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/DQ7F4_MiHm0?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/ 
    %br
    第五部：跑位
    %br
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/UmF7TktuL3g?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/UmF7TktuL3g?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
    %br
    第六部：防守的姿勢
    %br
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/d_E0Kqbq0ek?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/d_E0Kqbq0ek?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
  %section#gridSystem2
    .page-header
      %h1
        Nike Signature Moves
        %small Nike 拍了一系列很棒的教學教片
      =link_to "Nike Signature Moves", "http://www.youtube.com/playlist?list=PLE7ADFD5DE0FC8F2D", :onclick => "recordOutboundLink(this, 'Outbound Links', 'Nike');return false;"  

app/views/learn/index.html.haml
%h1
  %ul 整理一些對我自己有用的教學影片 by - Steven Ko
%h2 
  %li= link_to "iPhone 遊戲的程式教學影片", learn_ios_path, :onclick => "recordOutboundLink(this, 'Outbound Links', '#{learn_ios_path}');return false;"
  %li= link_to "籃球教學影片", learn_basketball_path, :onclick => "recordOutboundLink(this, 'Outbound Links', '#{learn_basketball_path}');return false;"
  %li= link_to "Java 教學影片", learn_java_path, :onclick => "recordOutboundLink(this, 'Outbound Links', '#{learn_java_path}');return false;"

app/views/learn/iphone_game.html.haml
.container
  /
    Masthead
    \==================================================
  %header#overview.jumbotron.subhead
    %h1 iPhone develop games
    %p.lead 整理一些開發 iPhone 遊戲的程式教學影片
    .subnav.subnav-fixed
      %ul.nav.nav-pills
        %li
          %a{:href => "#global"} Corona
        %li
          %a{:href => "#gridSystem"} cocos2D
        %li
          %a{:href => "#fluidGridSystem"} 用native code (object-c) 寫一個簡單遊戲
        %li
          %a{:href => "#gridCustomization"} unity3D
        %li
    (追加一篇
    =link_to "遊戲開發engine 的比較", "http://www.burtonsmediagroup.com/blog/2010/06/game-engines-for-iphone-ipad-android-cocos2d-corona-torque-unity-3d/"
    )
  %section#global
    .page-header
      %h1
        Corona
        %small Corona 是一套跨 andorid&iphone 的開發工具
      介紹：
      =link_to "corona简介-跨平台的手机App开发框架","http://blog.csdn.net/iamarmy/article/details/6619945"
      ,
      =link_to "App 開發效益再優化，你應該認識的 Corona SDK","http://techorange.com/2012/04/27/app-develop-corona/"
      %table.table
        %thead
          %tr
            %th Title
            %th 影片
        %tbody
          %tr
            %td iPhone Game Development with Corona: Hello World
            %td= duplicate_link_to "http://www.youtube.com/watch?v=GmS82aHW9zc&feature=plcp","Corona"
          %tr
            %td Android Game Development with Corona: Hello World
            %td= duplicate_link_to "http://www.youtube.com/watch?v=sTd0dGmwoOk&feature=plcp","Corona"
          %tr
            %td Android/iPhone/iPad dev with Corona:Working with Buttons-1
            %td= duplicate_link_to "http://www.youtube.com/watch?v=yCL8Ye43f0c&feature=plcp","Corona"
          %tr
            %td Android/iPhone/iPad dev with Corona:Working with Buttons-2
            %td= duplicate_link_to "http://www.youtube.com/watch?v=Qfe3K1x3sI4&feature=plcp","Corona"
          %tr
            %td Android, iPhone Corona tutorial - creating animation
            %td= duplicate_link_to "http://www.youtube.com/watch?v=cm_ys-M3Mng&feature=plcp","Corona"
          %tr
            %td Andorid/iPhone game development with Corona: Fade In and Out  
            %td= duplicate_link_to "http://www.youtube.com/watch?v=AFr9dwZ6Ly8&feature=plcp","Corona"
          %tr
            %td Android/iPhone/iPad Development with Corona-sound effects
            %td= duplicate_link_to "http://www.youtube.com/watch?v=M9p6XKk0kLo&feature=plcp","Corona"
          %tr
            %td iPhone/iPad/Android dev with Corona-orientation change
            %td= duplicate_link_to "http://www.youtube.com/watch?v=BVS5AMI-Ab0&feature=plcp","Corona"
          %tr
            %td Corona app development- Reading from SQLite database  
            %td= duplicate_link_to "http://www.youtube.com/watch?v=vN-5m-23zgY&feature=plcp","Corona"

    
  %section#gridSystem
    .page-header
      %h1
        cocos2D
        %small cocos2D 是一套跨 andorid&iphone 的開發工具, 目前是免費的哦！
      介紹：
      =link_to "Cocos2d簡介","http://bonjouryentinglai.wordpress.com/2009/11/30/cocos2d%E7%B0%A1%E4%BB%8B/"
      ,
      =link_to "cocos2d","http://baike.baidu.com/view/3800461.htm"
      %table.table
        %thead
          %tr
            %th Title
            %th 影片
        %tbody 
          %tr
            %td Cocos2D iPhone Tutorials - 1 - Downloading the Cocos2D Framework
            %td= duplicate_link_to "http://www.youtube.com/watch?v=pdVNahZb1PU&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 2 - Setting up a Cocos2D Template
            %td= duplicate_link_to "http://www.youtube.com/watch?v=B6SjWP9GcPU&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 3 - Creating Sprites  
            %td= duplicate_link_to "http://www.youtube.com/watch?v=mNJ0RoepySQ&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 4 - Making Stuff Move
            %td= duplicate_link_to "http://www.youtube.com/watch?v=WGtMMx4DxwM&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 5 - I Like It When You Touch Me
            %td= duplicate_link_to "http://www.youtube.com/watch?v=ogEsGZ2D-pw&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 6 - How to Create Menus and Menu Items
            %td= duplicate_link_to "http://www.youtube.com/watch?v=g_65LWdZH5U&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 7 - How to Create Scenes
            %td= duplicate_link_to "http://www.youtube.com/watch?v=ziQ6rYjqZO0&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 8 - Intro to Actions
            %td= duplicate_link_to "http://www.youtube.com/watch?v=9sdq1ueNqOM&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 9 - Some Examples of Actions
            %td= duplicate_link_to "http://www.youtube.com/watch?v=j_IJFsl-N-4&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 10 - Sequence, Spawn, and Repeat Actions
            %td= duplicate_link_to "http://www.youtube.com/watch?v=yX4RpU7wDA4&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 11 - Repeat, RepeatForever, and Ease
            %td= duplicate_link_to "http://www.youtube.com/watch?v=ohs-edNZ7Ks&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 12 - Creating RPG with Tiled Map
            %td= duplicate_link_to "http://www.youtube.com/watch?v=aFjQVoxLcpU&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 13 - Adding the Map to the Scene
            %td= duplicate_link_to "http://www.youtube.com/watch?v=cjduXkenf4w&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 14 - Using Object Layers in Tiled
            %td= duplicate_link_to "http://www.youtube.com/watch?v=ZCMT_LvdY-w&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 15 - Adding a Character to the RPG
            %td= duplicate_link_to "http://www.youtube.com/watch?v=Mtc0nXp6uDg&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 16 - Moving the Camera Around
            %td= duplicate_link_to "http://www.youtube.com/watch?v=isYIyPz-e_0&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 17 - Making the Dude Move!
            %td= duplicate_link_to "http://www.youtube.com/watch?v=smRmcOWuaKw&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 18 - Making Stuff to Bump Into
            %td= duplicate_link_to "http://www.youtube.com/watch?v=RTg3O3TiRc0&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 19 - Converting the Map to Coordinates
            %td= duplicate_link_to "http://www.youtube.com/watch?v=LNYxEl1v_mI&feature=plcp","cocos2D"
          %tr
            %td Cocos2D iPhone Tutorials - 20 - Watching the Dude Bump into Stuff!
            %td= duplicate_link_to "http://www.youtube.com/watch?v=NBVswCvgM7c&feature=plcp","cocos2D"

  %section#fluidGridSystem
    .page-header
      %h1
        用native code (object-c) 寫一個簡單遊戲
        %small making a simple iphone game
      %table.table
        %thead
          %tr
            %th Title
            %th 影片
        %tbody 
          %tr
            %td Making a simple iPhone game, part 1
            %td= duplicate_link_to "http://www.youtube.com/watch?v=aQfAj9pJuzw&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 2
            %td= duplicate_link_to "http://www.youtube.com/watch?v=iGwZoowB-6Y&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, Part 3
            %td= duplicate_link_to "http://www.youtube.com/watch?v=wceBxU4z74w&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, Part 4
            %td= duplicate_link_to "http://www.youtube.com/watch?v=eVjui65TS3E&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 5
            %td= duplicate_link_to "http://www.youtube.com/watch?v=oWvpmW5PH_E&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 6
            %td= duplicate_link_to "http://www.youtube.com/watch?v=5Q9DqF5XVgg&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 7
            %td= duplicate_link_to "http://www.youtube.com/watch?v=yoscnnrd-LQ&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 8
            %td= duplicate_link_to "http://www.youtube.com/watch?v=FjhK1EOq_pE&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 9
            %td= duplicate_link_to "http://www.youtube.com/watch?v=HX_iAW2bnvM&feature=plcp","native code (object-c)"
          %tr
            %td Making a simple iPhone game, part 10, FINAL!
            %td= duplicate_link_to "http://www.youtube.com/watch?v=hGfLBmRXSD4&feature=plcp","native code (object-c)"
  %section#gridCustomization
    .page-header
      %h1
        unity3D
        %small 很多人推薦 3D 遊戲的開發 engine
      =link_to "教學影片", "http://www.youtube.com/user/HowToMakeMobileGames/videos", :onclick => "recordOutboundLink(this, 'Outbound Links', 'unity3D');return false;"